### ISSUE TITLE
Minecraft startet nicht

### ISSUE THREAD

**Issue by Onako2** [Cee-1/Minecraft-Atlantis#1]
**Describe the bug**

**To Reproduce**
1. Java 17 installieren
2. Prism Launcher Pack importieren
3. Minecraft starten

**Expected behavior**
Minecraft sollte starten

**Desktop (please complete the following information):**
 - Windows 11
 - 0.4

**Additional context**
Minecraft zeigt an, dass die class Version 65 nicht erkannt wird.

**Comment by Cee-1** [comment]
Please install Java 21 to run Minecraft 1.21
